language: node_js
node_js:
  - "8.9.1"
install: true
cache:
  directories:
    - node_modules
notifications:
  email: false
script:
  - npm install
  - ng build --prod
  - ng build --aot -app ssr
  - npm install -g purifycss
  - purifycss "$(find ./dist -name styles.**)"  "$(find ./dist -name "**.js")" --min --info --out "$(find ./dist -name styles.**)"
  - npm install -g firebase-tools
  - cd functions && npm install && cd ..
  - cp -R dist ./functions/.
  - rm dist/index.html
  - firebase deploy --token "$FIREBASE_TOKEN"
