language: node_js
node_js:
  - "8.9.1"
install: true
script:
  - npm install
  - npm run build
  - npm install -g firebase-tools
  - cd functions && npm install && cd ..
  - firebase deploy --token "$FIREBASE_TOKEN"
